[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/network_apps/network
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/network_apps/upnp
[ERROR] 2018-11-21 08:52:44 apps.network_apps.wifi_debug.main: Kmodpy module not found!
Traceback (most recent call last):
  File "/home/boz/Desktop/ZPUI/apps/network_apps/wifi_debug/main.py", line 16, in <module>
    import kmodpy
ImportError: No module named kmodpy
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/network_apps/wifi_debug
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/network_apps/nmap
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/raspberrypi/tvservice
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/games/snake
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/games/g_2048
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/personal/pomodorod
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/personal/totp_2fa
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/calendar
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/clock
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/matrix
[INFO] 2018-11-21 08:52:44 apps.app_manager: Passed context to app apps/task_manager
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/task_manager
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/settings
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/stopwatch
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/scripts
[WARNING] 2018-11-21 08:52:44 context_manager: Context apps/zeromenu set a global callback on KEY_PROG2 (function: request_switch)
[INFO] 2018-11-21 08:52:44 apps.app_manager: Passed context to app apps/zeromenu
[INFO] 2018-11-21 08:52:44 apps.app_manager: Loaded app apps/zeromenu
[INFO] 2018-11-21 08:52:47 context_manager: Switching to apps/calendar context
[INFO] 2018-11-21 08:52:52 root: Caught KeyboardInterrupt
[INFO] 2018-11-21 12:01:41 root: Successfully loaded config from config.json
[INFO] 2018-11-21 12:01:41 context_manager: Switching to main context
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/media_apps/volume
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/media_apps/draw
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/media_apps/mocp
[INFO] 2018-11-21 12:01:41 apps.app_manager: Passed context to app apps/utils/screenshot
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/utils/screenshot
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/utils/spinner
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/utils/calculator
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/utils/file_browser
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/system_apps/lsusb
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/system_apps/shutdown
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/system_apps/system
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/system_apps/systemctl
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/system_apps/partitions
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/network_apps/wpa_cli
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/network_apps/network
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/network_apps/upnp
[ERROR] 2018-11-21 12:01:41 apps.network_apps.wifi_debug.main: Kmodpy module not found!
Traceback (most recent call last):
  File "/home/boz/Desktop/ZPUI/apps/network_apps/wifi_debug/main.py", line 16, in <module>
    import kmodpy
ImportError: No module named kmodpy
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/network_apps/wifi_debug
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/network_apps/nmap
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/raspberrypi/tvservice
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/games/snake
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/games/g_2048
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/personal/pomodorod
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/personal/totp_2fa
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/calendar
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/clock
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/matrix
[INFO] 2018-11-21 12:01:41 apps.app_manager: Passed context to app apps/task_manager
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/task_manager
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/settings
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/stopwatch
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/scripts
[WARNING] 2018-11-21 12:01:41 context_manager: Context apps/zeromenu set a global callback on KEY_PROG2 (function: request_switch)
[INFO] 2018-11-21 12:01:41 apps.app_manager: Passed context to app apps/zeromenu
[INFO] 2018-11-21 12:01:41 apps.app_manager: Loaded app apps/zeromenu
[INFO] 2018-11-21 12:01:47 context_manager: Switching to apps/calendar context
[ERROR] 2018-11-21 12:01:53 input.input: Exception global name 'GRID_HEIGHT' is not defined caused by callback <bound method DatePicker.move_up of <ui.date_picker.DatePicker object at 0x7f6ecd43ea90>> when key KEY_UP was received
[ERROR] 2018-11-21 12:01:53 input.input: Traceback (most recent call last):
  File "/home/boz/Desktop/ZPUI/input/input.py", line 249, in handle_callback
    callback()
  File "/home/boz/Desktop/ZPUI/ui/date_picker.py", line 157, in move_up
    self.selected_option['y'] = GRID_HEIGHT-1
NameError: global name 'GRID_HEIGHT' is not defined

[ERROR] 2018-11-21 12:01:53 input.input: Locals of the callback:
[ERROR] 2018-11-21 12:01:53 input.input: {'self': <ui.date_picker.DatePicker object at 0x7f6ecd43ea90>}
[INFO] 2018-11-21 12:02:03 root: Caught KeyboardInterrupt
[INFO] 2018-11-21 12:02:03 root: Successfully loaded config from config.json
[INFO] 2018-11-21 12:02:03 context_manager: Switching to main context
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/media_apps/volume
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/media_apps/draw
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/media_apps/mocp
[INFO] 2018-11-21 12:02:03 apps.app_manager: Passed context to app apps/utils/screenshot
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/utils/screenshot
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/utils/spinner
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/utils/calculator
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/utils/file_browser
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/system_apps/lsusb
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/system_apps/shutdown
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/system_apps/system
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/system_apps/systemctl
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/system_apps/partitions
[INFO] 2018-11-21 12:02:03 apps.app_manager: Loaded app apps/network_apps/wpa_cli
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/network_apps/network
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/network_apps/upnp
[ERROR] 2018-11-21 12:02:04 apps.network_apps.wifi_debug.main: Kmodpy module not found!
Traceback (most recent call last):
  File "/home/boz/Desktop/ZPUI/apps/network_apps/wifi_debug/main.py", line 16, in <module>
    import kmodpy
ImportError: No module named kmodpy
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/network_apps/wifi_debug
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/network_apps/nmap
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/raspberrypi/tvservice
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/games/snake
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/games/g_2048
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/personal/pomodorod
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/personal/totp_2fa
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/calendar
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/clock
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/matrix
[INFO] 2018-11-21 12:02:04 apps.app_manager: Passed context to app apps/task_manager
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/task_manager
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/settings
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/stopwatch
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/scripts
[WARNING] 2018-11-21 12:02:04 context_manager: Context apps/zeromenu set a global callback on KEY_PROG2 (function: request_switch)
[INFO] 2018-11-21 12:02:04 apps.app_manager: Passed context to app apps/zeromenu
[INFO] 2018-11-21 12:02:04 apps.app_manager: Loaded app apps/zeromenu
[INFO] 2018-11-21 12:02:07 context_manager: Switching to apps/calendar context
[INFO] 2018-11-21 12:05:34 root: Caught KeyboardInterrupt
[INFO] 2018-11-21 12:05:34 root: Successfully loaded config from config.json
[INFO] 2018-11-21 12:05:34 context_manager: Switching to main context
[INFO] 2018-11-21 12:05:34 apps.app_manager: Loaded app apps/media_apps/volume
[INFO] 2018-11-21 12:05:34 apps.app_manager: Loaded app apps/media_apps/draw
[INFO] 2018-11-21 12:05:34 apps.app_manager: Loaded app apps/media_apps/mocp
[INFO] 2018-11-21 12:05:34 apps.app_manager: Passed context to app apps/utils/screenshot
[INFO] 2018-11-21 12:05:34 apps.app_manager: Loaded app apps/utils/screenshot
[INFO] 2018-11-21 12:05:34 apps.app_manager: Loaded app apps/utils/spinner
[INFO] 2018-11-21 12:05:34 apps.app_manager: Loaded app apps/utils/calculator
[INFO] 2018-11-21 12:05:34 apps.app_manager: Loaded app apps/utils/file_browser
